---
- name: Ensure Wireshack is latest on web, and nfs servers
  hosts: web_servers, nfs_server
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
  - name: ensure wireshark is at the latest  version
    yum:
      name: wireshark
      state: present


- name: Ensure Wireshack is latest on LB server
  hosts: load_balancer
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
  - name: ensure wireshark is at the latest version
    apt:
      name: wireshark
      state: present

- name: update timezone on all servers
  hosts: all
  become: yes
  tasks:
   - command: timedatectl set-timezone Africa/Lagos