---
enable_apache_lb: true
load_balancer_is_required: true



























# all:
#   hosts:
#     172.31.28.140:
#     172.31.20.82:
#     172.31.28.71:
#     172.31.31.150:
#     172.31.29.105:
#   children:
#     web_servers:
#       children:
#         web1:
#           hosts:
#             172.31.28.140:
#             ansible_ssh_private_key_file:~/.ssh/mKey.pem:
#             ansible_use:ec2-user:
#         web2:
#           hosts:
#             172.31.20.82:
#             ansible_ssh_private_key_file:~/.ssh/mKey.pem:
#             ansible_use:ec2-user:
#     nfs:
#       hosts:
#         172.31.28.71:
#         ansible_ssh_private_key_file:~/.ssh/mKey.pem:
#         ansible_use:ec2-user:
#     db:
#       hosts:
#         172.31.31.150:
#         ansible_ssh_private_key_file:~/.ssh/mKey.pem:
#         ansible_use:ubuntu:
#     lb:
#       hosts:
#         172.31.29.105:
#         ansible_ssh_private_key_file:~/.ssh/mKey.pem:
#         ansible_use:ubuntu:


