pipeline {
  agent any
  environment{
    ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
  }
  parameters {
    string(name: 'inventory', defaultValue: '${inventory}', description: 'selecting the environment')
  }
  stages {
    stage("Initial cleanup") {
      steps {
        dir("${WORKSPACE}") {
          deleteDir()
        }
      }
    }
    stage('SCM Checkout') {
      steps {
        git(branch: 'main', url: 'https://github.com/Eebru-gzy/ansible-config-mgt')
      }
    }
    stage('Prepare Ansible For Execution') {
      steps {
        sh 'echo ${WORKSPACE}'
      }
    }
    stage('Execute Ansible') {
      steps {
        ansiblePlaybook credentialsId: 'Ansile-ssh', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yml'
      }
    }
    stage('Clean up') {
      steps {
        cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
      }
    }
  }
}
